pipeline{
    //def WORKSPACE = "/var/jenkins_home/workspace/front/cygi-front/"
    agent any
    
    stages{
        stage('Build Start'){
            steps{
                mattermostSend color: "#2A42EE", 
                    message: "Build STARTED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)",
                    endpoint: "https://meeting.ssafy.com/hooks/fzxngahki3bitej3t1osyhxeor",
                    channel: "all_back_jenkins"
            }
        }

        stage('Clone Repo'){
            steps{
                git url: 'https://lab.ssafy.com/s08-final/S08P31A806.git',
                    credentialsId: 'wnsdk', // Jenkins에서 설정한 credential의 ID
                    branch: 'deploy-front'
            }
        }

        stage('Deploy Docker'){
            steps{
                script{
                    //sh "docker build -t front:${env.BUILD_NUMBER} cygi-front/"
                    sh "docker stop front || true && docker rm front || true"
                    //sh "docker run -d -p 3000:3000 --name front front:${env.BUILD_NUMBER}"
                    sh "docker compose up -d"
                }
            }
        }

        stage('Finish'){
            steps{
                script{
                    sh "docker images -qf dangling=true | xargs -I{} docker rmi {}"
                }
            }
        }
    }

    post {
        success {
            mattermostSend color: "good", 
                message: "Build SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)",
                endpoint: "https://meeting.ssafy.com/hooks/fzxngahki3bitej3t1osyhxeor",
                channel: "all_back_jenkins"
        }
        failure {
            mattermostSend color: "danger", 
                message: "Build FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)",
                endpoint: "https://meeting.ssafy.com/hooks/fzxngahki3bitej3t1osyhxeor",
                channel: "all_back_jenkins"
        }
    }
}
