node{
    def WORKSPACE = "/var/jenkins_home/workspace/back-admin/cygi-admin/"
    def dockerImageTag = "back-admin-${env.BUILD_NUMBER}"

    try{
        stage('Clone Repo'){
            git url: 'https://lab.ssafy.com/s08-final/S08P31A806.git',
                credentialsId: 'wnsdk', // Jenkins에서 설정한 credential의 ID
                branch: 'deploy-back-admin'
        }

        stage('Gradle Build'){
            dir('cygi-admin/'){
                sh 'ls'
                sh 'chmod +x ./gradlew'
                sh './gradlew clean build'
                echo "Docker Image Tag Name: ${dockerImageTag}"
            }
        }

        stage('Build Docker'){
            dockerImage = docker.build("back-admin:${env.BUILD_NUMBER}", ".")
        }

        stage('Deploy Docker'){
            echo "Docker Image Tag Name: ${dockerImageTag}"
            // sh "docker stop back-admin || true && docker rm back-admin || true"
            sh "docker run --name back-admin -d -p 3000:8080 back-admin:${env.BUILD_NUMBER}"
            sh "docker image prune -a -f || true"
        }
    }catch(e){
        throw e
    }
}
