pipeline{
    //def WORKSPACE = "/var/jenkins_home/workspace/back-discovery/discovery/"
    agent any
    
    stages{
        stage('Build Start'){
            steps{
                mattermostSend color: "#2A42EE", 
                    message: "Build STARTED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)",
                    endpoint: "https://meeting.ssafy.com/hooks/fzxngahki3bitej3t1osyhxeor",
                    channel: "all_back_jenkins"
            }
        }

        stage('Clone Repo'){
            steps{
                git url: 'https://lab.ssafy.com/s08-final/S08P31A806.git',
                    credentialsId: 'swj', // Jenkins에서 설정한 credential의 ID
                    branch: 'deploy-back-discovery'
            }
        }

        stage('Gradle Build'){
            steps{
                dir('discovery/'){
                    sh 'ls'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh "docker build -t back-discovery:${env.BUILD_NUMBER} discovery/"
                }
            }
        }

        stage('Deploy Docker'){
            steps{
                script{
                    sh "docker stop back-discovery || true && docker rm back-discovery || true"
                    sh "docker run --name back-discovery -d -p 8761:8761 back-discovery:${env.BUILD_NUMBER}"
                    sh "docker image prune -a -f || true"
                }
            }
        }
    }

    post {
        success {
            mattermostSend color: "good", 
                message: "Build SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)",
                endpoint: "https://meeting.ssafy.com/hooks/fzxngahki3bitej3t1osyhxeor",
                channel: "all_back_jenkins"
        }
        failure {
            mattermostSend color: "danger", 
                message: "Build FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)",
                endpoint: "https://meeting.ssafy.com/hooks/fzxngahki3bitej3t1osyhxeor",
                channel: "all_back_jenkins"
        }
    }
}

